// src/data/DocumentsData.js

export const documentsData = [
  {
    id: 1,
    name: "Facture Fournisseur Janvier 2024",
    folder: "comptabilite",
    path: "comptabilite/factures",
    url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/DOC%20AUTO%20test%20-QCvBEymhd0Dj8kTCFDxQ0ICIto22aG.pdf",
    created_date: "2024-01-12T10:30:00Z",
    uploaded_by: "admin",
    description: "Facture fournisseur – janvier 2024",
  },
  {
    id: 2,
    name: "Relevé bancaire Février 2024",
    folder: "comptabilite",
    path: "comptabilite/releves",
    url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/DOC%20AUTO%20test%20-UDxH3MHUfwa4jWo9fG1Ms2px57Aks1.pdf",
    created_date: "2024-02-05T08:15:00Z",
    uploaded_by: "admin",
    description: "Relevé bancaire mensuel",
  },
  {
    id: 3,
    name: "Déclaration TVA T1 2024",
    folder: "fiscal",
    path: "fiscal/tva",
    url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/LM%20BG%20Logiciel-2XHybu36oW4i6tbXZMYgFzxXftduQA.pdf",
    created_date: "2024-04-10T14:00:00Z",
    uploaded_by: "admin",
    description: "Déclaration de TVA – T1 2024",
  },
  {
    id: 4,
    name: "Contrat de travail – CDI",
    folder: "social",
    path: "social/contrats",
    url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/LM%20BG%20Logiciel-JQ5WUxjTKV6isMGEuqS4gxl1DojaXz.pdf",
    created_date: "2023-09-01T09:00:00Z",
    uploaded_by: "admin",
    description: "Contrat de travail salarié CDI",
  },
  {
    id: 5,
    name: "Statuts de la société",
    folder: "juridique",
    path: "juridique/statuts",
    url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/LM%20BG%20Logiciel-JQ5WUxjTKV6isMGEuqS4gxl1DojaXz.pdf",
    created_date: "2022-03-18T11:45:00Z",
    uploaded_by: "client",
    description: "Statuts juridiques de la société",
  },
  //   {
  //     id: 6,
  //     name: "Documents Annexes",
  //     folder: "divers",
  //     path: "divers",
  //     url: "https://nrcdumqfyl1z2bwl.public.blob.vercel-storage.com/pdf/LM%20BG%20Logiciel-JQ5WUxjTKV6isMGEuqS4gxl1DojaXz.pdf",
  //     created_date: "2022-03-18T11:45:00Z",
  //     uploaded_by: "admin",
  //     description: "Documents outres catégories",
  //   },
];
