// appList.js (ou directement dans le composant)
export const appList = [
  {
    id: 1,
    name: "Mes Prêts pro",
    description: "Suivi de vos emprunts professionnels",
    category: "bancaire",
    icon: "Globe",
    url: "",
  },
  {
    id: 2,
    name: "Parc Auto",
    description: "Gestion de vos véhicules professionnels",
    category: "administratif",
    icon: "Globe",
    url: "",
  },
  {
    id: 3,
    name: "Inventaire",
    description: "Établir un inventaire de stock",
    category: "administratif",
    icon: "Globe",
    url: "",
  },
  {
    id: 4,
    name: "IK",
    description: "Calculateur d'indemnés kilométriques",
    category: "fiscal",
    icon: "Globe",
    url: "",
  },
  {
    id: 5,
    name: "MyALFA RHelp SIRH",
    description: "Système de gestion RH et paie",
    category: "social",
    icon: "Users",
    url: "",
  },
  {
    id: 6,
    name: "Impots.gouv",
    description: "Espace professionnel des impôts",
    category: "fiscal",
    icon: "Calculator",
    url: "https://www.impots.gouv.fr/accueil",
  },
  {
    id: 7,
    name: "URSSAF",
    description: "Déclarations et paiements URSSAF",
    category: "social",
    icon: "Users",
    url: "https://www.urssaf.fr/accueil.html",
  },
  {
    id: 8,
    name: "Net-entreprises",
    description: "Portail déclaratif social",
    category: "social",
    icon: "Building2",
    url: "https://www.net-entreprises.fr/",
  },
  {
    id: 9,
    name: "Infogreffe",
    description: "Registre du commerce",
    category: "administratif",
    icon: "FileText",
    url: "https://www.infogreffe.fr/",
  },
  {
    id: 10,
    name: "Ma banque Pro",
    description: "Espace bancaire professionnel",
    category: "bancaire",
    icon: "Calculator",
    url: "",
  },
  {
    id: 11,
    name: "CFE",
    description: "Centre de formalités des entreprises",
    category: "administratif",
    icon: "Globe",
    url: "https://www.cfe.urssaf.fr/",
  },
];
